version: '2.2'
services:
  # Elasticsearch endpoint which is exposed outside Elastic network
  elastic6:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.2
    container_name: elastic6
    restart: always
    environment:
      - "TZ=Europe/Sofia"
      - node.attr.storage=cold
      - cluster.name=intest
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms32g -Xmx32g"
      - action.destructive_requires_name=false
      - discovery.zen.ping.unicast.hosts=elastic.sofia.ifao.net
      - "discovery.zen.ping_timeout=60s"
      - "discovery.zen.commit_timeout=60s"
      - "ping_timeout=60s"
      - "ping_retries=10"
      - "cluster.info.update.interval=60s"
      - node.name=elastic6
      - node.master=true
      - node.data=true
      - node.ingest=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /root/data/ces6:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      elasticnet:
        ipv4_address: 172.20.0.36
  elastic7:
    depends_on:
     - elastic6
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.2
    container_name: elastic7
    restart: always
    environment:
      - "TZ=Europe/Sofia"
      - node.attr.storage=cold
      - cluster.name=intest
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - action.destructive_requires_name:false
      - discovery.zen.ping.unicast.hosts=elastic6,elastic.sofia.ifao.net
      - node.name=elastic7
      - node.master=true
      - node.data=true
      - node.ingest=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /root/data/ces7:/usr/share/elasticsearch/data
    networks:
      elasticnet:
        ipv4_address: 172.20.0.37
  elastic8:
    depends_on:
     - elastic6
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.2
    container_name: elastic8
    restart: always
    environment:
      - "TZ=Europe/Sofia"
      - node.attr.storage=cold
      - cluster.name=intest
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - action.destructive_requires_name:false
      - discovery.zen.ping.unicast.hosts=elastic6,elastic.sofia.ifao.net
      - node.name=elastic8
      - node.master=true
      - node.data=true
      - node.ingest=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /root/data/ces8:/usr/share/elasticsearch/data
    networks:
      elasticnet:
        ipv4_address: 172.20.0.38

networks:
  elasticnet:
    name: elasticnet
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
