-
  name: Kibana Playbook
  hosts: all
  # Requirement for hanrdening provided by ITS
  # -k to ask for SSH access ()
  # -K to ask for becoming sudo
  remote_user: '{{ user }}'
  become: true
  become_method: sudo
  become_user: root
  vars_files:
    - vars.yml
  vars:
    elk:
      - "kibana-{{ kibana_version }}"
    required:
      - bind-utils
    gpg:
      - "{{ gpg_key }}"
  tasks:
    - name: Importing GPG key for Elastic.co
      rpm_key:
        key: '{{ item }}'
        state: present
      with_items: '{{ gpg }}'
    - name: Deploying Elastic.co repository
      yum_repository:
        name: elastic
        description: Elastic.co repository for 6.x packages
        baseurl: https://artifacts.elastic.co/packages/6.x/yum
        gpgcheck: yes
        gpgkey: '{{ gpg_key }}'
        enabled: yes
        state: present
    # Required for ITS hanrdening, initial permissions are 0600
    - name: Setting Elastic.co repository 644 permission
      file:
        path: /etc/yum.repos.d/elastic.repo
        mode: 0644
    - name: Installing required packages
      yum:
        name: '{{ required }}'
        state: present
    - name: Installing Kibana {{ kibana_version }}
      yum:
        name: '{{ elk }}'
        state: present
        enablerepo: elastic
        update_cache: yes
      # shell: 'yum install kibana-6.3.1'
    - name: Starting and enabling Kibana service
      service:
        name: kibana
        state: started
        enabled: yes
    - name: Applying configuration for Kibana
      copy:
        src: kibana.config.yml
        dest: /etc/kibana/kibana.yml
