{
 "title": "Elastic Server",
 "description": "VM Monitoring",
 "tags": [
  "vm",
  "elastic"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_boot_time{job=\"elastic\"}, instance)"
   },
   {
    "name": "port",
    "label": "port",
    "query": "label_values(node_boot_time, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node:$port\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=~\"$node:$port\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=~\"$node:$port\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu{instance=~\"$node:$port\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu{mode='idle',instance=~\"$node:$port\"}[5m])))) * 100) / count(count(node_cpu{instance=~\"$node:$port\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node:$port\"}) /  count(count(node_cpu{instance=~\"$node:$port\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"$node:$port\"}) /  count(count(node_cpu{instance=~\"$node:$port\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "singlestat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable{instance=~\"$node:$port\"} * 100) / node_memory_MemTotal{instance=~\"$node:$port\"})"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "singlestat",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Processes State",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Processes" }
   ],
   "targets": [
    {
     "expr": "node_procs_blocked{instance=~\"$node:$port\"}",
     "legendFormat": "Processes blocked waiting for I/O to complete"
    },
    {
     "expr": "node_procs_running{instance=~\"$node:$port\"}",
     "legendFormat": "Processes in runnable state"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu{mode=\"system\",instance=~\"$node:$port\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu{mode='user',instance=~\"$node:$port\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu{mode='iowait',instance=~\"$node:$port\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu{mode=~\".*irq\",instance=~\"$node:$port\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$node:$port\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu{mode='idle',instance=~\"$node:$port\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_bytes_read{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}} - Bytes read"
    },
    {
     "expr": "irate(node_disk_bytes_written{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}} - Bytes written"
    }
   ]
  },
  {
   "title": "Memory Writeback and Dirty",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Writeback{instance=~\"$node:$port\"}",
     "legendFormat": "Writeback - Memory which is actively being written back to disk"
    },
    {
     "expr": "node_memory_WritebackTmp{instance=~\"$node:$port\"}",
     "legendFormat": "WritebackTmp - Memory used by FUSE for temporary writeback buffers"
    },
    {
     "expr": "node_memory_Dirty{instance=~\"$node:$port\"}",
     "legendFormat": "Dirty - Memory which is waiting to get written back to the disk"
    }
   ]
  },
  {
   "title": "Network Traffic by Packets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_packets{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic Drop",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_drop{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}} - Receive drop"
    },
    {
     "expr": "irate(node_network_transmit_drop{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}} - Transmit drop"
    }
   ]
  }
 ]
}