{
 "title": "Elastic Stack @ Docker",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [
  "elastic",
  "docker"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load",
   "type": "singlestat",
   "description": "Max load of CPU - 3200",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu{instance=~\"elastic:9100\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu{mode='idle',instance=~\"elastic:9100\"}[5m])))) * 100) / count(count(node_cpu{instance=~\"elastic:9100\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal{job=\"elastic\"}) - sum(node_memory_MemFree{job=\"elastic\"}) - sum(node_memory_Buffers{job=\"elastic\"}) - sum(node_memory_Cached{job=\"elastic\"})) / sum(node_memory_MemTotal{job=\"elastic\"} )) * 100"
    }
   ]
  },
  {
   "title": "RAM Management",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Cached{job=\"elastic\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_Buffers{job=\"elastic\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_MemFree{job=\"elastic\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "sum(node_memory_MemTotal{job=\"elastic\"} - node_memory_MemFree{job=\"elastic\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemTotal{job=\"elastic\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Root disk space usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 14, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{device!=\"rootfs\", job=\"elastic\"}) - sum(node_filesystem_free{device!=\"rootfs\", job=\"elastic\"})) / sum(node_filesystem_size{device!=\"rootfs\", job=\"elastic\"})"
    }
   ]
  },
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{job=\"cadvisor\", image!=\"\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 9 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{job=\"cadvisor\", image!=\"\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Running containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(container_last_seen{job=\"cadvisor\", image!=\"\"})"
    }
   ]
  },
  {
   "title": "CPU Usage (max 3200%)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{job=\"cadvisor\", image!=\"\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "VIRT Memory Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{job=\"cadvisor\", image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{job=\"cadvisor\", image!=\"\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{job=\"cadvisor\", image!=\"\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}