---
  # Disables firewalld
  - name: Stop firewalld
    service:
      name: firewalld
      state: stopped
      enabled: no

  # Starts Docker
  - name: Start Docker
    service:
      name: docker
      state: started
      enabled: no
