---
  elk_version: 6.3.1
  cadvisor_version: latest
  portainer_version: latest
  redis_version: latest
  jenkins_version: 2.60.3-alpine
  kibana_config: kibana.config.yml
  elasticsearch_config: elasticsearch.config.yml
  gpg_key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  bitbucket_repo: repository.secure.ifao.net:7443/scm/cicd/elastic.git
  clone_dest: /root/elastic
  cert_name: ifao-root-ca.crt
  cert_path: /etc/pki/tls/certs